const albumsActionTypes = {
    ADD_CURRENT_ALBUM: "ADD_CURRENT_ALBUM",
    CLEAR_CURRENT_ALBUM: "CLEAR_CURRENT_ALBUM",
    ADD_CURRENT_SONGS: "ADD_CURRENT_SONGS",
    UPDATE_ALBUMS: "UPDATE_ALBUMS",
    FETCH_ALBUMS_START: "FETCH_ALBUMS_START",
    FETCH_ALBUMS_SUCCESS: "FETCH_ALBUMS_SUCCESS",
    FETCH_ALBUMS_FAILURE: "FETCH_ALBUMS_FAILURE"
}

export default albumsActionTypes;